### ISSUE TITLE
Dogcom在登录界面显示

### ISSUE THREAD

**Issue by ghost** [mchome/luci-app-dogcom#4]
luci登录界面顶栏上会显示dogcom而其他不会

**Comment by mchome** [comment]
???

**Comment by ghost** [comment]
像这样，但不知道什么原因
![无标题](https://user-images.githubusercontent.com/61447805/92476068-f6121480-f210-11ea-8b08-8307aff92615.png)

**Comment by mchome** [comment]
![image](https://user-images.githubusercontent.com/7392658/92476363-67ea5e00-f211-11ea-8c6a-798f46e4d863.png)

15.05 😆

**Comment by ghost** [comment]
我用的snapshot，可是稳定版19.03 5Ghz wifi不能用。换个material主题没事，我还是先用着吧

**Comment by ghost** [comment]
换成19.07.4没事了
